apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: user-api-config
  name: user-api-config
  namespace: default
data:
  DB_NAME: users
  DB_HOSTNAME: mysql
  DB_PORT: "3306"
  DB_USERNAME: user1
