apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-persistent-volume-claim
  name: mysql-persistent-volume-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi